version: 1
disable_existing_loggers: false


formatters:
    stream:
        format: "%(message)4s"
    file:
        format: "%(message)4s"
#        format: "%(asctime)s:%(filename)s:%(lineno)4s - %(funcName)s():    %(levelname)-8s %(message)4s"

        
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: stream
        stream: ext://sys.stdout

    debug_file_handler:
        class: hxrsnd.utils.RotatingFileHandlerRelativePath
        level: DEBUG
        formatter: file
        filename: ../logs/debug.log
        maxBytes: 20971520 # 20MB
        backupCount: 10
        mode: a
        delay: 0

    info_file_handler:
        class: hxrsnd.utils.RotatingFileHandlerRelativePath
        level: INFO
        formatter: file
        filename: ../logs/info.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        mode: a
        delay: 0
        
    warn_file_handler:
        class: hxrsnd.utils.RotatingFileHandlerRelativePath
        level: WARN
        formatter: file
        filename: ../logs/warn.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        mode: a
        delay: 0

    error_file_handler:
        class: hxrsnd.utils.RotatingFileHandlerRelativePath
        level: ERROR
        formatter: file
        filename: ../logs/errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        mode: a
        delay: 0

    critical_file_handler:
        class: hxrsnd.utils.RotatingFileHandlerRelativePath
        level: CRITICAL
        formatter: file
        filename: ../logs/critical.log
        maxBytes: 10485760 # 10MB
        backupCount: 10
        mode: a
        delay: 0

        
root:
    level: DEBUG
    handlers: [info_file_handler, error_file_handler, critical_file_handler, debug_file_handler, warn_file_handler]
    propogate: no

    
loggers:
    <hxrsnd>:
        level: INFO
        handlers: [console]
        propogate: no
