{% set data = load_setup_py_data() %}

package:
  name: hxrsnd
  version : {{ data.get('version') }}

source:
  path: ..

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python >=3.6,<3.10
    - setuptools
  run:
    - python >=3.6,<3.10
    - ipython
    - numpy
    - pandas
    - lmfit
    - simplejson
    - pyyaml
    - coloredlogs
    - super_state_machine
    - pswalker >=1.0.5
    - pcdsdevices >=4.0.0
    - pyepics
  run_constrained:
    - pyqt <5.15

test:
  imports:
    - hxrsnd

about:
  home: https://github.com/pcdshub/hxrsnd
  license: SLAC Open License
  summary: XCS Split and Delay Device Classes
